language: python
install:
    - pip install -r requirements.txt
    - pip install tox
script: tox
after_success:
    - bash <(curl -s https://codecov.io/bash)

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.6
          env: TOXENV=py36
